const ACTIONS_TYPES = {
    GET_ALL_FOODS: 'GET_ALL_FOODS',
    ADD_TO_CART: 'ADD_TO_CART',
    REDUCE_FROM_CART: 'READUCE_FROM_CART',
    RECEIVE_POSTS: 'RECEIVE_POSTS',
    REQUEST_POSTS: 'REQUEST_POSTS',
    INVALIDATE_SUBREDDIT: 'INVALIDATE_SUBREDDIT'
}

export default {...ACTIONS_TYPES}